#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define MAX_NOME 30
#define DIM_PERGUNTA 100
#define MAX_PERGUNTAS 40
#define MAX_ALUNOS 20
#define MAX_STRING 100
#define MIN_ANO 2018
#define MAX_ANO 2019

#endif // CONSTANTES_H_INCLUDED
